In [458]:
import pandas as pd
import numpy as np

from pathlib import Path

In [459]:
pd.options.display.max_rows = 100
pd.options.display.min_rows = 20
pd.options.display.max_columns = None

In [460]:
ROOT_PATH = Path(Path.cwd()).resolve().parent
DATA_PATH = ROOT_PATH/'data'/'raw'
PROCESSED_PATH = ROOT_PATH/'data'/'processed'

# Funciones

In [461]:
def comprobacion_por_puntos(df, equipos, jornadas):
    
    for equipo in equipos:
        for jornada in jornadas:
            condicion = (df['EQUIPO'] == equipo) & (df['JORNADA'] == jornada)

            PTS_Jugadores = df[condicion]['PTS'].sum()
            PTS_Oficiales = df.loc[condicion, 'RESULTADO'].iloc[0]

            if PTS_Jugadores > PTS_Oficiales:
                print(f'❌ERROR en {equipo}, jornada {jornada}❌ La suma de PTS de los jugadores es mayor a la puntuación oficial')
            elif PTS_Jugadores < PTS_Oficiales:
                print(f'❌ERROR en {equipo}, jornada {jornada}❌ La puntuación oficial es mayor que suma de PTS de los jugadores')
            elif PTS_Jugadores == PTS_Oficiales:
                print(f'✅ La comprobación por puntos ha tenido éxito. {equipo}, jornada {jornada}')
            else:
                print('⚠️ERROR DESCONOCIDO')

In [462]:
def comprobar_tiempo(df, equipo, jornada, variable_segundos):
    for equipo in equipos:
        for jornada in jornadas:
            cond1 = df[(df['EQUIPO'] == equipo) & (df['JORNADA'] == jornada)][variable_segundos].sum() == (40*60*5*2)
            cond2 = df[(df['EQUIPO'] == equipo) & (df['JORNADA'] == jornada)][variable_segundos].sum() == (45*60*5*2)
            cond3 = df[(df['EQUIPO'] == equipo) & (df['JORNADA'] == jornada)][variable_segundos].sum() == (50*60*5*2)
            no_prorroga = df[(df['EQUIPO'] == equipo) & (df['JORNADA'] == jornada)]['CUARTO'].max() == 4
            una_prorroga = df[(df['EQUIPO'] == equipo) & (df['JORNADA'] == jornada)]['CUARTO'].max() == 5
            dos_prorrogas = df[(df['EQUIPO'] == equipo) & (df['JORNADA'] == jornada)]['CUARTO'].max() == 6

            if cond1 & no_prorroga:
                print(f'✅ Tiempo correcto. {equipo} - Jornada {jornada}')
            elif cond2 & una_prorroga:
                print(f'✅ Tiempo correcto. {equipo} - Jornada {jornada}')
            elif cond3 & dos_prorrogas:
                print(f'✅ Tiempo correcto. {equipo} - Jornada {jornada}')
            elif no_prorroga:
                print(f'❌ERROR❌ Tiempo incorrecto. {equipo} - Jornada {jornada}: {df[(df['EQUIPO'] == equipo) & (df['JORNADA'] == jornada)][variable_segundos].sum()} / {40*60*5*2} segundos')
            elif una_prorroga:
                print(f'❌ERROR❌ Tiempo incorrecto. {equipo} - Jornada {jornada}: {df[(df['EQUIPO'] == equipo) & (df['JORNADA'] == jornada)][variable_segundos].sum()} / {45*60*5*2} segundos')
            elif dos_prorrogas:
                print(f'❌ERROR❌ Tiempo incorrecto. {equipo} - Jornada {jornada}: {df[(df['EQUIPO'] == equipo) & (df['JORNADA'] == jornada)][variable_segundos].sum()} / {50*60*5*2} segundos')
            else:
                print(f'❌ERROR❌ Error desconocido (Más de dos prórrogas?)')

In [463]:
def extraer_dorsal(jugador):
    if len(jugador) > 1 and jugador[1] == ' ':
        return jugador[0]
    else:
        return jugador[:2]

In [464]:
def comprobar_totales(df, part1, part2, total):
    check = (df[total].fillna(0) == df[part1] + df[part2]).all()
    if check:
        print('✅Comprobación con ÉXITO')
    else:
        print('⚠️⚠️ALERTA⚠️⚠️. La comprobación ha detectado un error')

In [465]:
def resultado_rival(df, equipos, jornadas):
    df['RESULTADO_RIVAL'] = 0
    for equipo in equipos:
        for jornada in jornadas:
            cond_equipo = (df['EQUIPO'] == equipo) & (df['JORNADA'] == jornada)
            rival = df.loc[cond_equipo, 'RIVAL'].iloc[0]
            cond_rival = (df['EQUIPO'] == rival) & (df['JORNADA'] == jornada)

            resultado_rival = df.loc[cond_rival, 'RESULTADO'].iloc[0]
            df['RESULTADO_RIVAL'] = np.where(cond_equipo, resultado_rival, df['RESULTADO_RIVAL'])

# Creación de DataFrame principal

In [466]:
df = pd.read_csv(DATA_PATH/'RAW DATA.csv')

# Comprobación de la recolección de datos

In [467]:
df['EQUIPO'].dropna(inplace=True)

In [468]:
equipos = df['EQUIPO'].unique().tolist()
jornadas = df['JORNADA'].unique().tolist()

comprobacion_por_puntos(df, equipos, jornadas)

✅ La comprobación por puntos ha tenido éxito. UNI, jornada 1
✅ La comprobación por puntos ha tenido éxito. UNI, jornada 2
✅ La comprobación por puntos ha tenido éxito. UNI, jornada 3
✅ La comprobación por puntos ha tenido éxito. UNI, jornada 4
✅ La comprobación por puntos ha tenido éxito. SBB, jornada 1
✅ La comprobación por puntos ha tenido éxito. SBB, jornada 2
✅ La comprobación por puntos ha tenido éxito. SBB, jornada 3
✅ La comprobación por puntos ha tenido éxito. SBB, jornada 4
✅ La comprobación por puntos ha tenido éxito. BUR, jornada 1
✅ La comprobación por puntos ha tenido éxito. BUR, jornada 2
✅ La comprobación por puntos ha tenido éxito. BUR, jornada 3
✅ La comprobación por puntos ha tenido éxito. BUR, jornada 4
✅ La comprobación por puntos ha tenido éxito. GIR, jornada 1
✅ La comprobación por puntos ha tenido éxito. GIR, jornada 2
✅ La comprobación por puntos ha tenido éxito. GIR, jornada 3
✅ La comprobación por puntos ha tenido éxito. GIR, jornada 4
✅ La comprobación por puntos ha tenido éxito. LLT, jornada 1
✅ La comprobación por puntos ha tenido éxito. LLT, jornada 2
✅ La comprobación por puntos ha tenido éxito. LLT, jornada 3
✅ La comprobación por puntos ha tenido éxito. LLT, jornada 4
✅ La comprobación por puntos ha tenido éxito. BAX, jornada 1
✅ La comprobación por puntos ha tenido éxito. BAX, jornada 2
✅ La comprobación por puntos ha tenido éxito. BAX, jornada 3
✅ La comprobación por puntos ha tenido éxito. BAX, jornada 4
✅ La comprobación por puntos ha tenido éxito. HIO, jornada 1
✅ La comprobación por puntos ha tenido éxito. HIO, jornada 2
✅ La comprobación por puntos ha tenido éxito. HIO, jornada 3
✅ La comprobación por puntos ha tenido éxito. HIO, jornada 4
✅ La comprobación por puntos ha tenido éxito. BRE, jornada 1
✅ La comprobación por puntos ha tenido éxito. BRE, jornada 2
✅ La comprobación por puntos ha tenido éxito. BRE, jornada 3
✅ La comprobación por puntos ha tenido éxito. BRE, jornada 4
✅ La comprobación por puntos ha tenido éxito. COV, jornada 1
✅ La comprobación por puntos ha tenido éxito. COV, jornada 2
✅ La comprobación por puntos ha tenido éxito. COV, jornada 3
✅ La comprobación por puntos ha tenido éxito. COV, jornada 4
✅ La comprobación por puntos ha tenido éxito. JOV, jornada 1
✅ La comprobación por puntos ha tenido éxito. JOV, jornada 2
✅ La comprobación por puntos ha tenido éxito. JOV, jornada 3
✅ La comprobación por puntos ha tenido éxito. JOV, jornada 4
✅ La comprobación por puntos ha tenido éxito. RMB, jornada 1
✅ La comprobación por puntos ha tenido éxito. RMB, jornada 2
✅ La comprobación por puntos ha tenido éxito. RMB, jornada 3
✅ La comprobación por puntos ha tenido éxito. RMB, jornada 4
✅ La comprobación por puntos ha tenido éxito. DGC, jornada 1
✅ La comprobación por puntos ha tenido éxito. DGC, jornada 2
✅ La comprobación por puntos ha tenido éxito. DGC, jornada 3
✅ La comprobación por puntos ha tenido éxito. DGC, jornada 4
✅ La comprobación por puntos ha tenido éxito. CAZ, jornada 1
✅ La comprobación por puntos ha tenido éxito. CAZ, jornada 2
✅ La comprobación por puntos ha tenido éxito. CAZ, jornada 3
✅ La comprobación por puntos ha tenido éxito. CAZ, jornada 4
✅ La comprobación por puntos ha tenido éxito. BKN, jornada 1
✅ La comprobación por puntos ha tenido éxito. BKN, jornada 2
✅ La comprobación por puntos ha tenido éxito. BKN, jornada 3
❌ERROR en BKN, jornada 4❌ La suma de PTS de los jugadores es mayor a la puntuación oficial
✅ La comprobación por puntos ha tenido éxito. UCM, jornada 1
✅ La comprobación por puntos ha tenido éxito. UCM, jornada 2
✅ La comprobación por puntos ha tenido éxito. UCM, jornada 3
✅ La comprobación por puntos ha tenido éxito. UCM, jornada 4
✅ La comprobación por puntos ha tenido éxito. MBA, jornada 1
✅ La comprobación por puntos ha tenido éxito. MBA, jornada 2
✅ La comprobación por puntos ha tenido éxito. MBA, jornada 3
✅ La comprobación por puntos ha tenido éxito. MBA, jornada 4
✅ La comprobación por puntos ha tenido éxito. VBC, jornada 1
✅ La comprobación por puntos ha tenido éxito. VBC, jornada 2
✅ La comprobación por puntos ha tenido éxito. VBC, jornada 3
✅ La comprobación por puntos ha tenido éxito. VBC, jornada 4
✅ La comprobación por puntos ha tenido éxito. BAR, jornada 1
✅ La comprobación por puntos ha tenido éxito. BAR, jornada 2
✅ La comprobación por puntos ha tenido éxito. BAR, jornada 3
✅ La comprobación por puntos ha tenido éxito. BAR, jornada 4

# Data engienieering

## Titular

In [469]:
# Arreglamos el formato de la columna para que se presente como bool
df['TITULAR'] = df['TITULAR'].fillna(0).astype(bool)

## Local

In [470]:
# Arreglamos el formato de la columna para que se presente como bool
df['LOCAL'] = df['LOCAL'].fillna(0).astype(bool)

## Apellido

In [471]:
df["Apellido"] = df["JUGADOR"].str.extract(
    r'^\d+\s+[A-ZÁÉÍÓÚÜÑ]\.\s+(.+)$'
)

df["Apellido"] = np.where(
    df["Apellido"].isna(),
    df["EQUIPO"],
    df["Apellido"]
)

## Dorsal

In [472]:
# El dorsal de jugador es únicamente el número con 1 o 2 cifras
df['#'] = df['JUGADOR'].apply(extraer_dorsal)

# El dorsal para la estadística de equipo presenta el código del equipo en cuestión
df['#'] = np.where(df['#'] == 'Eq', df['EQUIPO'], df['#'])

# Se elimina la columna JUGADOR, que contiene información redundante
df.drop(columns='JUGADOR', inplace=True)

## Clave única de jugador

In [473]:
df['KEY'] = df['EQUIPO'] + df['#'] + df['Apellido']

## Tiros

In [474]:
# Separamos los tiros en anotados y totales. También creamos una categoría para los fallados. El porcentaje de acierto lo calcularemos directamente en PowerBI

# Tiros de 2
df[['T2A', 'T2I']] = (
    df['T2']
    .str.split('/', expand=True)
    .apply(pd.to_numeric, errors='coerce')
    .fillna(0)
    .astype(int)
)
df['T2F'] = df['T2I'] - df['T2A']

# Triples
df[['T3A', 'T3I']] = (
    df['T3']
    .str.split('/', expand=True)
    .apply(pd.to_numeric, errors='coerce')
    .fillna(0)
    .astype(int)
)
df['T3F'] = df['T3I'] - df['T3A']

# Tiros de Campo
df['TCA'] = df['T2A'] + df['T3A']
df['TCI'] = df['T2I'] + df['T3I']
df['TCF'] = df['T2F'] + df['T3F']


# Tiros libres
df[['TLA', 'TLI']] = (
    df['TL']
    .str.split('/', expand=True)
    .apply(pd.to_numeric, errors='coerce')
    .fillna(0)
    .astype(int)
)
df['TLF'] = df['TLI'] - df['TLA']


# Eliminamos columnas innecesarias
cols_eliminar = [
    'T2', 'T2%',
    'T3', 'T3%',
    'TL', 'TL%'
]
df = df.drop(columns=cols_eliminar)

In [475]:
comprobar_totales(df,'T2A', 'T2F', 'T2I')

✅Comprobación con ÉXITO

In [476]:
comprobar_totales(df,'T3A', 'T3F', 'T3I')

✅Comprobación con ÉXITO

In [477]:
comprobar_totales(df,'TCA', 'TCF', 'TCI')

✅Comprobación con ÉXITO

In [478]:
comprobar_totales(df,'TLA', 'TLF', 'TLI')

✅Comprobación con ÉXITO

## Rebotes

In [479]:
comprobar_totales(df,'RO', 'RD', 'RT')

✅Comprobación con ÉXITO

## Tapones

In [480]:
df = df.rename(columns={'TR':'TAPR'})

## Faltas

In [481]:
df = df.rename(columns={'FR':'FPR'})

## Minutos

In [482]:
# Se cambia la información del tiempo jugado a segundos en SEG y se elimina MIN
df['SEG'] = (
    df['MIN']
    .fillna('00:00')
    .str.split(':')
    .apply(lambda x: int(x[0]) * 60 + int(x[1]))
)

df.drop(columns='MIN', inplace=True)

In [483]:
mask_equipo = df['#'] == df['EQUIPO']

df.loc[mask_equipo, 'SEG'] = (
    df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['SEG']
    .transform('sum')
)

In [484]:
comprobar_tiempo(df, equipos, jornadas, 'SEG')

✅ Tiempo correcto. UNI - Jornada 1
✅ Tiempo correcto. UNI - Jornada 2
✅ Tiempo correcto. UNI - Jornada 3
✅ Tiempo correcto. UNI - Jornada 4
✅ Tiempo correcto. SBB - Jornada 1
✅ Tiempo correcto. SBB - Jornada 2
✅ Tiempo correcto. SBB - Jornada 3
✅ Tiempo correcto. SBB - Jornada 4
✅ Tiempo correcto. BUR - Jornada 1
✅ Tiempo correcto. BUR - Jornada 2
✅ Tiempo correcto. BUR - Jornada 3
✅ Tiempo correcto. BUR - Jornada 4
✅ Tiempo correcto. GIR - Jornada 1
✅ Tiempo correcto. GIR - Jornada 2
✅ Tiempo correcto. GIR - Jornada 3
✅ Tiempo correcto. GIR - Jornada 4
✅ Tiempo correcto. LLT - Jornada 1
✅ Tiempo correcto. LLT - Jornada 2
✅ Tiempo correcto. LLT - Jornada 3
✅ Tiempo correcto. LLT - Jornada 4
✅ Tiempo correcto. BAX - Jornada 1
✅ Tiempo correcto. BAX - Jornada 2
✅ Tiempo correcto. BAX - Jornada 3
✅ Tiempo correcto. BAX - Jornada 4
✅ Tiempo correcto. HIO - Jornada 1
✅ Tiempo correcto. HIO - Jornada 2
✅ Tiempo correcto. HIO - Jornada 3
✅ Tiempo correcto. HIO - Jornada 4
✅ Tiempo correcto. BRE - Jornada 1
✅ Tiempo correcto. BRE - Jornada 2
✅ Tiempo correcto. BRE - Jornada 3
✅ Tiempo correcto. BRE - Jornada 4
✅ Tiempo correcto. COV - Jornada 1
✅ Tiempo correcto. COV - Jornada 2
✅ Tiempo correcto. COV - Jornada 3
✅ Tiempo correcto. COV - Jornada 4
✅ Tiempo correcto. JOV - Jornada 1
✅ Tiempo correcto. JOV - Jornada 2
✅ Tiempo correcto. JOV - Jornada 3
✅ Tiempo correcto. JOV - Jornada 4
✅ Tiempo correcto. RMB - Jornada 1
✅ Tiempo correcto. RMB - Jornada 2
✅ Tiempo correcto. RMB - Jornada 3
✅ Tiempo correcto. RMB - Jornada 4
✅ Tiempo correcto. DGC - Jornada 1
✅ Tiempo correcto. DGC - Jornada 2
✅ Tiempo correcto. DGC - Jornada 3
✅ Tiempo correcto. DGC - Jornada 4
✅ Tiempo correcto. CAZ - Jornada 1
✅ Tiempo correcto. CAZ - Jornada 2
✅ Tiempo correcto. CAZ - Jornada 3
✅ Tiempo correcto. CAZ - Jornada 4
✅ Tiempo correcto. BKN - Jornada 1
✅ Tiempo correcto. BKN - Jornada 2
✅ Tiempo correcto. BKN - Jornada 3
✅ Tiempo correcto. BKN - Jornada 4
✅ Tiempo correcto. UCM - Jornada 1
✅ Tiempo correcto. UCM - Jornada 2
✅ Tiempo correcto. UCM - Jornada 3
✅ Tiempo correcto. UCM - Jornada 4
✅ Tiempo correcto. MBA - Jornada 1
✅ Tiempo correcto. MBA - Jornada 2
✅ Tiempo correcto. MBA - Jornada 3
✅ Tiempo correcto. MBA - Jornada 4
✅ Tiempo correcto. VBC - Jornada 1
✅ Tiempo correcto. VBC - Jornada 2
✅ Tiempo correcto. VBC - Jornada 3
✅ Tiempo correcto. VBC - Jornada 4
✅ Tiempo correcto. BAR - Jornada 1
✅ Tiempo correcto. BAR - Jornada 2
✅ Tiempo correcto. BAR - Jornada 3
✅ Tiempo correcto. BAR - Jornada 4

## Resultado Rival

In [485]:
resultado_rival(df, equipos, jornadas)

## Victoria

In [486]:
df['VICTORIA'] = df['RESULTADO'] > df['RESULTADO_RIVAL']

## Valoración
Eliminamos la valoración para calcularla por nuestra cuenta

In [487]:
df = df.drop(columns='VAL')

In [488]:
# Valoración
df['VAL'] = (
    df['PTS']
    + df['RT']
    + df['ASI']
    + df['REC']
    + df['TAP']
    + df['FPR']
    - df['TCF']
    - df['TLF']
    - df['PER']
    - df['TAPR']
    - df['FP']
)

# Nulos

In [489]:
df.isna().sum()

EQUIPO             0
JORNADA            0
RIVAL              0
RESULTADO          0
LOCAL              0
CUARTO             0
TITULAR            0
PTS                0
RO                 0
RD                 0
RT                 0
ASI                0
PER                0
REC                0
TAP                0
TAPR               0
MAT                0
FP                 0
FPR                0
+/-                0
Apellido           0
#                  0
KEY                0
T2A                0
T2I                0
T2F                0
T3A                0
T3I                0
T3F                0
TCA                0
TCI                0
TCF                0
TLA                0
TLI                0
TLF                0
SEG                0
RESULTADO_RIVAL    0
VICTORIA           0
VAL                0
dtype: int64

In [490]:
df.fillna(0,inplace=True)
df.isna().sum()

EQUIPO             0
JORNADA            0
RIVAL              0
RESULTADO          0
LOCAL              0
CUARTO             0
TITULAR            0
PTS                0
RO                 0
RD                 0
RT                 0
ASI                0
PER                0
REC                0
TAP                0
TAPR               0
MAT                0
FP                 0
FPR                0
+/-                0
Apellido           0
#                  0
KEY                0
T2A                0
T2I                0
T2F                0
T3A                0
T3I                0
T3F                0
TCA                0
TCI                0
TCF                0
TLA                0
TLI                0
TLF                0
SEG                0
RESULTADO_RIVAL    0
VICTORIA           0
VAL                0
dtype: int64

# Tabla separada: PARTIDOS

In [491]:
df_partidos = df[
    [
        'JORNADA',
        'EQUIPO',
        'RESULTADO',
        'RIVAL',
        'RESULTADO_RIVAL',
        'LOCAL',
        'VICTORIA'
    ]
].drop_duplicates()

# Nos quedamos únicamente con los partidos en los que local sea cierto (un registro por partido)
df_partidos = df_partidos[df_partidos['LOCAL']].reset_index(drop=True)
df_partidos = df_partidos.drop(columns='LOCAL')

# Renombramos columnas para presentar los equipos local y visitante
df_partidos = df_partidos.rename(columns={'EQUIPO': 'LOCAL', 'RIVAL': 'VISITANTE'})

# Cambiamos la columna VICTORIA para que muestre al equipo vencedor
df_partidos['VICTORIA'] = np.where(df_partidos['RESULTADO'] > df_partidos['RESULTADO_RIVAL'], df_partidos['LOCAL'], df_partidos['VISITANTE'])

# Cambiamos la columna RESULTADO para que muestre el resultado en formato LOCAL - VISITANTE
df_partidos['RESULTADO'] = df_partidos['RESULTADO'].astype(str) + ' - ' + df_partidos['RESULTADO_RIVAL'].astype(str)

# Eliminamos la columna RESULTADO_RIVAL que ya no contiene información útil
df_partidos = df_partidos.drop(columns= 'RESULTADO_RIVAL')

In [492]:
df_partidos

    JORNADA LOCAL  RESULTADO VISITANTE VICTORIA
0         1   UNI    86 - 68       SBB      UNI
1         1   BUR    97 - 79       GIR      BUR
2         1   LLT   104 - 93       BAX      LLT
3         1   HIO    87 - 68       BRE      HIO
4         1   COV    75 - 87       JOV      JOV
5         1   RMB    81 - 71       DGC      RMB
6         1   CAZ   107 - 88       BKN      CAZ
7         1   UCM    95 - 64       MBA      UCM
8         1   VBC    93 - 81       BAR      VBC
9         2   GIR    71 - 93       UCM      UCM
10        2   MBA    64 - 96       LLT      LLT
11        2   DGC    72 - 81       UNI      UNI
12        2   BAX    83 - 68       COV      BAX
13        2   JOV    89 - 86       CAZ      JOV
14        2   BAR    86 - 91       HIO      HIO
15        2   BRE   90 - 113       VBC      VBC
16        2   SBB    95 - 85       BUR      SBB
17        2   BKN  105 - 100       RMB      BKN
18        3   BAX    80 - 87       DGC      DGC
19        3   MBA  115 - 113       GIR      MBA
20        3   LLT    96 - 80       UCM      LLT
21        3   CAZ    84 - 88       BRE      BRE
22        3   JOV   101 - 69       SBB      JOV
23        3   RMB    90 - 80       BUR      RMB
24        3   HIO    78 - 99       VBC      VBC
25        3   COV    80 - 83       BKN      BKN
26        3   UNI    77 - 83       BAR      BAR
27        4   HIO    99 - 90       COV      HIO
28        4   BAR   100 - 85       BRE      BAR
29        4   LLT    95 - 79       UNI      LLT
30        4   BUR   89 - 102       CAZ      CAZ
31        4   GIR    85 - 81       DGC      GIR
32        4   UCM    89 - 84       BKN      UCM
33        4   SBB    81 - 71       MBA      SBB
34        4   VBC   102 - 90       JOV      VBC
35        4   RMB    87 - 75       BAX      RMB

# Variables para Estadísticas Avanzadas

## Estadísticas por partido
Como las estadísticas aparecen por cuarto, se cambia el nombre de esas columnas por Estadístico_Q y se crea el estadístico por partido

In [493]:
estadisticos = ['PTS', 'RO', 'RD', 'RT', 'ASI', 'PER', 
    'REC', 'TAP', 'TAPR', 'MAT', 'FP', 'FPR', 
    '+/-', 'T2A', 'T2I', 'T2F', 
    'T3A', 'T3I','T3F', 'TCA', 'TCI', 'TCF', 
    'TLA', 'TLI', 'TLF', 'SEG', 'VAL']

df = df.rename(columns={col: f'{col}_Q' for col in estadisticos})
# df = df.rename(columns={'SEG':'SEG_Q'})

for col in estadisticos:
    
    df[col] = df.groupby(['EQUIPO', 'JORNADA', '#'])[f'{col}_Q'].transform('sum')

# df['SEG'] = df.groupby(['EQUIPO', 'JORNADA'])['SEG_Q'].transform('sum')

In [494]:
comprobar_tiempo(df, equipos, jornadas, 'SEG_Q')

✅ Tiempo correcto. UNI - Jornada 1
✅ Tiempo correcto. UNI - Jornada 2
✅ Tiempo correcto. UNI - Jornada 3
✅ Tiempo correcto. UNI - Jornada 4
✅ Tiempo correcto. SBB - Jornada 1
✅ Tiempo correcto. SBB - Jornada 2
✅ Tiempo correcto. SBB - Jornada 3
✅ Tiempo correcto. SBB - Jornada 4
✅ Tiempo correcto. BUR - Jornada 1
✅ Tiempo correcto. BUR - Jornada 2
✅ Tiempo correcto. BUR - Jornada 3
✅ Tiempo correcto. BUR - Jornada 4
✅ Tiempo correcto. GIR - Jornada 1
✅ Tiempo correcto. GIR - Jornada 2
✅ Tiempo correcto. GIR - Jornada 3
✅ Tiempo correcto. GIR - Jornada 4
✅ Tiempo correcto. LLT - Jornada 1
✅ Tiempo correcto. LLT - Jornada 2
✅ Tiempo correcto. LLT - Jornada 3
✅ Tiempo correcto. LLT - Jornada 4
✅ Tiempo correcto. BAX - Jornada 1
✅ Tiempo correcto. BAX - Jornada 2
✅ Tiempo correcto. BAX - Jornada 3
✅ Tiempo correcto. BAX - Jornada 4
✅ Tiempo correcto. HIO - Jornada 1
✅ Tiempo correcto. HIO - Jornada 2
✅ Tiempo correcto. HIO - Jornada 3
✅ Tiempo correcto. HIO - Jornada 4
✅ Tiempo correcto. BRE - Jornada 1
✅ Tiempo correcto. BRE - Jornada 2
✅ Tiempo correcto. BRE - Jornada 3
✅ Tiempo correcto. BRE - Jornada 4
✅ Tiempo correcto. COV - Jornada 1
✅ Tiempo correcto. COV - Jornada 2
✅ Tiempo correcto. COV - Jornada 3
✅ Tiempo correcto. COV - Jornada 4
✅ Tiempo correcto. JOV - Jornada 1
✅ Tiempo correcto. JOV - Jornada 2
✅ Tiempo correcto. JOV - Jornada 3
✅ Tiempo correcto. JOV - Jornada 4
✅ Tiempo correcto. RMB - Jornada 1
✅ Tiempo correcto. RMB - Jornada 2
✅ Tiempo correcto. RMB - Jornada 3
✅ Tiempo correcto. RMB - Jornada 4
✅ Tiempo correcto. DGC - Jornada 1
✅ Tiempo correcto. DGC - Jornada 2
✅ Tiempo correcto. DGC - Jornada 3
✅ Tiempo correcto. DGC - Jornada 4
✅ Tiempo correcto. CAZ - Jornada 1
✅ Tiempo correcto. CAZ - Jornada 2
✅ Tiempo correcto. CAZ - Jornada 3
✅ Tiempo correcto. CAZ - Jornada 4
✅ Tiempo correcto. BKN - Jornada 1
✅ Tiempo correcto. BKN - Jornada 2
✅ Tiempo correcto. BKN - Jornada 3
✅ Tiempo correcto. BKN - Jornada 4
✅ Tiempo correcto. UCM - Jornada 1
✅ Tiempo correcto. UCM - Jornada 2
✅ Tiempo correcto. UCM - Jornada 3
✅ Tiempo correcto. UCM - Jornada 4
✅ Tiempo correcto. MBA - Jornada 1
✅ Tiempo correcto. MBA - Jornada 2
✅ Tiempo correcto. MBA - Jornada 3
✅ Tiempo correcto. MBA - Jornada 4
✅ Tiempo correcto. VBC - Jornada 1
✅ Tiempo correcto. VBC - Jornada 2
✅ Tiempo correcto. VBC - Jornada 3
✅ Tiempo correcto. VBC - Jornada 4
✅ Tiempo correcto. BAR - Jornada 1
✅ Tiempo correcto. BAR - Jornada 2
✅ Tiempo correcto. BAR - Jornada 3
✅ Tiempo correcto. BAR - Jornada 4

In [495]:
df[(df['EQUIPO'] == 'UNI') & (df['JORNADA'] == 1) & (df['#'] == '0')]

,EQUIPO,JORNADA,RIVAL,RESULTADO,LOCAL,CUARTO,TITULAR,PTS_Q,RO_Q,RD_Q,RT_Q,ASI_Q,PER_Q,REC_Q,TAP_Q,TAPR_Q,MAT_Q,FP_Q,FPR_Q,+/-_Q,Apellido,#,KEY,T2A_Q,T2I_Q,T2F_Q,T3A_Q,T3I_Q,T3F_Q,TCA_Q,TCI_Q,TCF_Q,TLA_Q,TLI_Q,TLF_Q,SEG_Q,RESULTADO_RIVAL,VICTORIA,VAL_Q,PTS,RO,RD,RT,ASI,PER,REC,TAP,TAPR,MAT,FP,FPR,+/-,T2A,T2I,T2F,T3A,T3I,T3F,TCA,TCI,TCF,TLA,TLI,TLF,SEG,VAL
0,UNI,1,SBB,86,True,1,True,0,1,2,3,0,0,0,0,0,0,1,0,-4,Pérez,0,UNI0Pérez,0,1,1,0,1,1,0,2,2,0,0,0,294,68,True,0,6,1,2,3,0,0,0,0,0,1,2,1,3,2,3,1,0,2,2,2,5,3,2,2,0,744,5
13,UNI,1,SBB,86,True,2,True,4,0,0,0,0,0,0,0,0,1,0,0,8,Pérez,0,UNI0Pérez,2,2,0,0,0,0,2,2,0,0,0,0,266,68,True,4,6,1,2,3,0,0,0,0,0,1,2,1,3,2,3,1,0,2,2,2,5,3,2,2,0,744,5
26,UNI,1,SBB,86,True,3,True,2,0,0,0,0,0,0,0,0,0,1,1,-1,Pérez,0,UNI0Pérez,0,0,0,0,1,1,0,1,1,2,2,0,184,68,True,1,6,1,2,3,0,0,0,0,0,1,2,1,3,2,3,1,0,2,2,2,5,3,2,2,0,744,5
39,UNI,1,SBB,86,True,4,True,0,0,0,0,0,0,0,0,0,0,0,0,0,Pérez,0,UNI0Pérez,0,0,0,0,0,0,0,0,0,0,0,0,0,68,True,0,6,1,2,3,0,0,0,0,0,1,2,1,3,2,3,1,0,2,2,2,5,3,2,2,0,744,5

In [496]:
df['MIN_Q'] = df['SEG_Q']/60
df['MIN'] = df['SEG']/60

In [497]:
df.head()

,EQUIPO,JORNADA,RIVAL,RESULTADO,LOCAL,CUARTO,TITULAR,PTS_Q,RO_Q,RD_Q,RT_Q,ASI_Q,PER_Q,REC_Q,TAP_Q,TAPR_Q,MAT_Q,FP_Q,FPR_Q,+/-_Q,Apellido,#,KEY,T2A_Q,T2I_Q,T2F_Q,T3A_Q,T3I_Q,T3F_Q,TCA_Q,TCI_Q,TCF_Q,TLA_Q,TLI_Q,TLF_Q,SEG_Q,RESULTADO_RIVAL,VICTORIA,VAL_Q,PTS,RO,RD,RT,ASI,PER,REC,TAP,TAPR,MAT,FP,FPR,+/-,T2A,T2I,T2F,T3A,T3I,T3F,TCA,TCI,TCF,TLA,TLI,TLF,SEG,VAL,MIN_Q,MIN
0,UNI,1,SBB,86,True,1,True,0,1,2,3,0,0,0,0,0,0,1,0,-4,Pérez,0,UNI0Pérez,0,1,1,0,1,1,0,2,2,0,0,0,294,68,True,0,6,1,2,3,0,0,0,0,0,1,2,1,3,2,3,1,0,2,2,2,5,3,2,2,0,744,5,4.9,12.400000
1,UNI,1,SBB,86,True,1,True,2,0,0,0,0,0,0,0,0,0,1,1,-4,Balcerowski,2,UNI2Balcerowski,0,1,1,0,0,0,0,1,1,2,2,0,294,68,True,1,17,0,4,4,0,1,0,0,1,1,4,6,3,4,6,2,1,1,0,5,7,2,6,7,1,1229,18,4.9,20.483333
2,UNI,1,SBB,86,True,1,False,3,0,0,0,1,1,0,0,0,0,0,0,2,Kalinoski,4,UNI4Kalinoski,0,0,0,1,1,0,1,1,0,0,0,0,276,68,True,3,6,2,1,3,2,1,0,0,0,0,2,2,17,1,3,2,1,1,0,2,4,2,1,2,1,987,7,4.6,16.450000
3,UNI,1,SBB,86,True,1,False,2,0,0,0,0,0,1,0,0,0,0,2,-2,Barreiro,7,UNI7Barreiro,1,1,0,0,0,0,1,1,0,0,1,1,366,68,True,4,4,0,1,1,0,0,1,0,0,0,1,3,-6,1,1,0,0,1,1,1,2,1,2,3,1,816,6,6.1,13.600000
4,UNI,1,SBB,86,True,1,False,2,0,0,0,0,0,0,0,0,0,0,1,1,Díaz,9,UNI9Díaz,1,1,0,0,0,0,1,1,0,0,0,0,306,68,True,3,6,1,0,1,2,1,0,0,0,0,0,3,7,1,1,0,1,1,0,2,2,0,1,2,1,1058,10,5.1,17.633333

In [498]:
# Datos totales del partido
df['MIN_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['MIN_Q'].transform('sum') / 5
df['T2A_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['T2A_Q'].transform('sum')
df['T2I_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['T2I_Q'].transform('sum')
df['T2F_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['T2F_Q'].transform('sum')
df['T3A_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['T3A_Q'].transform('sum')
df['T3I_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['T3I_Q'].transform('sum')
df['T3F_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['T3F_Q'].transform('sum')
df['TCA_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['TCA_Q'].transform('sum')
df['TCI_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['TCI_Q'].transform('sum')
df['TCF_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['TCF_Q'].transform('sum')
df['TLA_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['TLA_Q'].transform('sum')
df['TLI_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['TLI_Q'].transform('sum')
df['TLF_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['TLF_Q'].transform('sum')
df['RT_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['RT_Q'].transform('sum')
df['RO_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['RO_Q'].transform('sum')
df['RD_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['RD_Q'].transform('sum')
df['ASI_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['ASI_Q'].transform('sum')
df['PER_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['PER_Q'].transform('sum')
df['REC_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['REC_Q'].transform('sum')
df['TAP_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['TAP_Q'].transform('sum')
df['TAPR_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['TAPR_Q'].transform('sum')
df['MAT_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['MAT_Q'].transform('sum')
df['FP_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['FP_Q'].transform('sum')
df['FPR_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['FPR_Q'].transform('sum')
df['VAL_Eq'] = df.groupby(['EQUIPO', 'JORNADA'])['VAL_Q'].transform('sum')

# Datos del cuarto
df['MIN_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['MIN_Q'].transform('sum') / 5
df['PTS_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['PTS_Q'].transform('sum')
df['T2A_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['T2A_Q'].transform('sum')
df['T2I_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['T2I_Q'].transform('sum')
df['T2F_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['T2F_Q'].transform('sum')
df['T3A_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['T3A_Q'].transform('sum')
df['T3I_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['T3I_Q'].transform('sum')
df['T3F_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['T3F_Q'].transform('sum')
df['TCA_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['TCA_Q'].transform('sum')
df['TCI_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['TCI_Q'].transform('sum')
df['TCF_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['TCF_Q'].transform('sum')
df['TLA_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['TLA_Q'].transform('sum')
df['TLI_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['TLI_Q'].transform('sum')
df['TLF_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['TLF_Q'].transform('sum')
df['RT_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['RT_Q'].transform('sum')
df['RO_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['RO_Q'].transform('sum')
df['RD_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['RD_Q'].transform('sum')
df['ASI_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['ASI_Q'].transform('sum')
df['PER_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['PER_Q'].transform('sum')
df['REC_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['REC_Q'].transform('sum')
df['TAP_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['TAP_Q'].transform('sum')
df['TAPR_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['TAPR_Q'].transform('sum')
df['MAT_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['MAT_Q'].transform('sum')
df['FP_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['FP_Q'].transform('sum')
df['FPR_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['FPR_Q'].transform('sum')
df['VAL_Eq_Q'] = df.groupby(['EQUIPO', 'JORNADA', 'CUARTO'])['VAL_Q'].transform('sum')

# Estadística avanzada

In [499]:
# Posesiones del equipo
df['POS_Eq'] = df['TCI_Eq'] - df['RO_Eq'] + df['PER_Eq'] + 0.44 * df['TLI_Eq']

In [500]:
# Estadísticas del rival
df = df.merge(
    df[['EQUIPO', 'JORNADA', 'RT_Eq', 'RD_Eq', 'RO_Eq', 'T2I_Eq', 'T3I_Eq', 'POS_Eq']]
        .drop_duplicates()
        .rename(columns={
            'EQUIPO': 'RIVAL',
            'RT_Eq': 'RT_Rival',
            'RD_Eq': 'RD_Rival', 
            'RO_Eq': 'RO_Rival', 
            'T2I_Eq': 'T2I_Rival',
            'T3I_Eq': 'T3I_Rival',
            'POS_Eq': 'POS_Rival'
        }),
    on=['RIVAL', 'JORNADA'],
    how='left'
)

In [501]:
# Ritmo del partido
df['PACE'] = 40 * ((df['POS_Eq'] + df['POS_Rival']) / 2) / df['MIN_Eq']

## Estadísticas de Equipo

- %TR = Porcentaje real de tiro
- %TE = Porcenaje de tiro efectivo
- RT3 = Ratio de triples
- RTL = Ratio de tiros libres
- %RO = Porcenaje de rebotes ofensivos capturados
- %RD = Porcenaje de rebotes defensivos capturados
- %REB = Porcenaje de rebotes capturados
- %ASI = Porcenaje de asistencias
- %ROB = Porcenaje de robos
- %TAP = Porcenaje de tapones
- %PER = Porcenaje de pérdidas
- %USO = Porcenaje de uso

In [502]:
# Eficiencia ofensiva, defensiva y neta del equipo
df['ORtg'] = df['RESULTADO'] * 100 / df['POS_Eq']
df['DRtg'] = df['RESULTADO_RIVAL'] * 100 / df['POS_Rival']
df['NRtg'] = df['ORtg'] - df['DRtg']

# Effective Field Goal (Ajusta el valor extra del Triple)
df['%TE_Eq'] = (df['TCA_Eq'] + 0.5 * df['T3A_Eq']) / df['TCI_Eq']
df['%TE_Eq'] = np.where(df['TCI_Eq'] == 0, 0, df['%TE_Eq'])

# True Shooting % (Mide eficiencia real de anotación incluyendo TL)
df['%TR_Eq'] = df['RESULTADO'] / (2 * (df['TCI_Eq'] + 0.44 * df['TLI_Eq']))
df['%TR_Eq'] = np.where((2 * (df['TCI_Eq'] + 0.44 * df['TLI_Eq'])) == 0, 0, df['%TR_Eq'])

# Assist % (Estimación del porcentaje de canastas asistidas)
df['%ASI_Eq'] = df['ASI_Eq'] / df['TCA_Eq']
df['%ASI_Eq'] = np.where(df['TCA_Eq'] == 0, 0, df['%ASI_Eq'])

# Turnover % (Qué porcentaje de posesiones termina en pérdida)
df['%PER_Eq'] = df['PER_Eq']/df['POS_Eq']
df['%PER_Eq'] = np.where(df['POS_Eq'] == 0, 0, df['%PER_Eq'])

# Offensive Rebound % (Qué porcentaje de rebotes ofensivos posibles captura el equipo)
df['%RO_Eq'] = df['RO_Eq'] / (df['RO_Eq'] + df['RD_Rival'])
df['%RO_Eq'] = np.where((df['RO_Eq'] + df['RD_Rival']) == 0, 0, df['%RO_Eq'])

# Deffensive Rebound % (Qué porcentaje de rebotes defensivos posibles captura el equipo)
df['%RD_Eq'] = df['RD_Eq'] / (df['RD_Eq'] + df['RO_Rival'])
df['%RD_Eq'] = np.where((df['RD_Eq'] + df['RO_Rival']) == 0, 0, df['%RD_Eq'])

# Total Rebound % 
df['%RT_Eq'] = df['RT_Eq'] / (df['RT_Eq'] + df['RT_Rival'])
df['%RT_Eq'] = np.where((df['RT_Eq'] + df['RT_Rival']) == 0, 0, df['%RT_Eq'])

# Ratio de Tiros Libres
df['RTL_Eq'] = df['TLI_Eq'] / df['TCI_Eq']
df['RTL_Eq'] = np.where(df['TCI_Eq'] == 0, 0, df['RTL_Eq'])

# Ratio de Triples Intentados
df['RT3I_Eq'] = df['T3I_Eq'] / df['TCI_Eq']
df['RT3I_Eq'] = np.where(df['TCI_Eq'] == 0, 0, df['RT3I_Eq'])

In [503]:
# Porcentaje de tiros de 2, 3 y tiros libres anotados
df['%T2_Eq'] = df['T2A_Eq'] / df['T2I_Eq']
df['%T2_Eq'] = np.where(df['T2I_Eq'] == 0, 0, df['%T2_Eq'])
df['%T3_Eq'] = df['T3A_Eq'] / df['T3I_Eq']
df['%T3_Eq'] = np.where(df['T3I_Eq'] == 0, 0, df['%T3_Eq'])
df['%TL_Eq'] = df['TLA_Eq'] / df['TLI_Eq']
df['%TL_Eq'] = np.where(df['TLI_Eq'] == 0, 0, df['%TL_Eq'])

## Estadísticas de Jugador

In [504]:
# % de Uso (Estima qué porcentaje de posesiones del equipo “consume” el jugador mientras está en pista)
    # Interpretación: 30% = jugador ultra dominante        ~20% = rol medio       <15% = jugador de bajo volumen
df['%USO'] = (df['TCI'] + 0.44 * df['TLI'] + df['PER']) * (df['MIN_Eq']) / (df['MIN'] * df['POS_Eq'])
df['%USO'] = np.where((df['MIN'] * df['POS_Eq']) == 0, 0, df['%USO'])

# True Shooting % (Mide eficiencia real de anotación incluyendo TL)
df['%TR'] = df['PTS'] / (2 * (df['TCI'] + 0.44 * df['TLI']))
df['%TR'] = np.where((2 * (df['TCI'] + 0.44 * df['TLI'])) == 0, 0, df['%TR'])

# Effective Field Goal (Ajusta el valor extra del Triple)
df['%TE'] = (df['TCA'] + 0.5 * df['T3A']) / df['TCI']
df['%TE'] = np.where(df['TCI'] == 0, 0, df['%TE'])

# Assist % (Estimación del porcentaje de canastas de compañeros asistidas por el jugador mientras está en pista)
df['%ASI'] = 100 * df['ASI'] / ((df['MIN']/(df['MIN_Eq']) * df['TCA_Eq']) - df['TCA'])
df['%ASI'] = np.where(((df['MIN']/(df['MIN_Eq']) * df['TCA_Eq']) - df['TCA']) == 0, 0, df['%ASI'])

# Turnover % (Qué porcentaje de posesiones usadas termina en pérdida)
df['%PER'] = 100 * df['PER'] / (df['TCI'] + 0.44 * df['TLI'] + df['PER'])
df['%PER'] = np.where((df['TCI'] + 0.44 * df['TLI'] + df['PER']) == 0, 0, df['%PER'])

# Offensive Rebound % (Porcentaje de rebotes ofensivos disponibles capturados)
df['%RO'] = 100 * df['RO'] * (df['MIN_Eq']) / (df['MIN'] * (df['RO_Eq'] + df['RD_Rival']))
df['%RO'] = np.where((df['MIN'] * (df['RO_Eq'] + df['RD_Rival'])) == 0, 0, df['%RO'])

# Deffensive Rebound % (Porcentaje de rebotes defensivos disponibles capturados)
df['%RD'] = 100 * df['RD'] * (df['MIN_Eq']) / (df['MIN'] * (df['RD_Eq'] + df['RO_Rival']))
df['%RD'] = np.where((df['MIN'] * (df['RD_Eq'] + df['RO_Rival'])) == 0, 0, df['%RD'])

# Total Rebound % 
df['%RT'] = 100 * df['RT'] * (df['MIN_Eq']) / (df['MIN'] * (df['RT_Eq'] + df['RT_Rival']))
df['%RT'] = np.where((df['MIN'] * (df['RT_Eq'] + df['RT_Rival'])) == 0, 0, df['%RT'])

# Steal % (Estimación del porcentaje de posesiones rivales robadas)
df['%REC'] = 100 * df['REC'] * (df['MIN_Eq']) / (df['MIN'] * df['POS_Rival'])
df['%REC'] = np.where((df['MIN'] * df['POS_Rival']) == 0, 0, df['%REC'])

# Tapones % (Porcentaje de tiros de 2 rivales taponados)
df['%TAP'] = 100 * df['TAP'] * (df['MIN_Eq']) / (df['MIN'] * (df['T2I_Rival'] - df['T3I_Rival']))
df['%TAP'] = np.where((df['MIN'] * (df['T2I_Rival'] - df['T3I_Rival'])) == 0, 0, df['%TAP'])

# Ratio de Tiros Libres
df['RTL'] = df['TLI'] / df['TCI']
df['RTL'] = np.where(df['TCI'] == 0, 0, df['RTL'])

# Ratio de Triples Intentados
df['RT3I'] = df['T3I'] / df['TCI']
df['RT3I'] = np.where(df['TCI'] == 0, 0, df['RT3I'])

# Puntos por tiro
df['PPT'] = df['PTS'] / df['TCI']
df['PPT'] = np.where(df['TCI'] == 0, 0, df['PPT'])



# # Eficiencia ofensiva individual
# df['TmScPoss'] = df['TCA_Eq'] + (1 - ( 1 - df['TCA_Eq'] / df['TLI_Eq'])**2) * 0.44 * df['TLI_Eq']
# df['TmPoss'] = df['TCI_Eq'] + 0.44 * df['TLI_Eq'] + df['PER_Eq']


# df['qAST'] = df['MIN'] / (df['MIN_Eq']) * (1.14 * (df['ASI_Eq'] - df['ASI'])/(df['TCA_Eq']-df['TCA'])) + ((df['ASI_Eq']/df['MIN_Eq'] * df['MIN'] * 5 - df['ASI']) / ((df['TCA_Eq'] * df['MIN'] * 5) / df['MIN_Eq'] - df['TCA'])) * (1 - df['MIN']/df['MIN_Eq'])
# df['fact_off_Eq'] = df['TmScPoss'] / (df['TCI_Eq'] + 0.44 * df['TLI_Eq'] + df['PER_Eq'])
# df['efic_anot_Eq'] = df['TmScPoss'] / df['TmPoss']
# df['TmROWeight'] = ((1 - df['efic_anot_Eq']) * df['RO_Eq']) / ((1 - df['efic_anot_Eq']) * df['RO_Eq'] + df['RD_Rival'])

# df['pprod_TC'] = 2*(df['T2A'] + 1.5 * df['T3A']) * df['qAST']
# df['pprod_ASI'] = 2*((df['TCA_Eq'] - df['TCA'] + 0.5 * (df['T3A_Eq'] - df['T3A'])) / (df['TCA_Eq'] - df['TCA'])) * df['ASI']
# df['pprod_RO'] = df['RO'] * df['efic_anot_Eq'] * df['TmROWeight']

# df['posesiones_usadas'] = df['TCI'] + 0.44 * df['TLI'] + df['PER']
# df['puntos_producidos'] = df['pprod_TC'] + df['pprod_ASI'] + df['pprod_RO']

# variables_para_ORtg = ['TmScPoss', 'TmPoss', 'qAST', 'fact_off_Eq', 'efic_anot_Eq', 'TmROWeight', 'pprod_TC', 'pprod_ASI', 'pprod_RO', 'posesiones_usadas', 'puntos_producidos']

# df['ORtg'] = 100 * df['puntos_producidos'] / df['posesiones_usadas']


# # Plan B ORtg
# df['pprod_TC'] = 2*(df['T2A'] + 1.5 * df['T3A'])
# df['pprod_ASI'] = 2*((df['TCA_Eq'] - df['TCA'] + 0.5 * (df['T3A_Eq'] - df['T3A'])) / (df['TCA_Eq'] - df['TCA'])) * df['ASI']
# df['pprod_RO'] = df['RO'] * df['efic_anot_Eq'] * df['TmROWeight']

# df['posesiones_usadas'] = df['TCI'] + 0.44 * df['TLI'] + df['PER']
# df['puntos_producidos'] = df['pprod_TC'] + df['pprod_ASI'] + df['pprod_RO']


# df['ORtg2'] = 100 * df['puntos_producidos'] / df['posesiones_usadas']
# df = df.drop(columns=variables_para_ORtg)

# NULOS

In [505]:
df.isna().sum().sum()

np.int64(0)

# Preparación de DF

In [506]:
base = [
'ID_partido',
'KEY',
'#',
'EQUIPO',
'JORNADA',
'RESULTADO',
'RIVAL',
'RESULTADO_RIVAL',
'LOCAL',
'TITULAR',
'VICTORIA']

por_partido = [
'MIN',
'SEG',
'PTS',
'TCA',
'TCI',
'TCF',
'T2A',
'T2I',
'T2F',
'T3A',
'T3I',
'T3F',
'TLA',
'TLI',
'TLF',
'RO',
'RD',
'RT',
'ASI',
'PER',
'REC',
'TAP',
'TAPR',
'FP',
'FPR',
'MAT',
'+/-',
'VAL']

por_cuarto = [
'MIN_Q',
'SEG_Q',
'PTS_Q',
'TCA_Q',
'TCI_Q',
'TCF_Q',
'T2A_Q',
'T2I_Q',
'T2F_Q',
'T3A_Q',
'T3I_Q',
'T3F_Q',
'TLA_Q',
'TLI_Q',
'TLF_Q',
'RO_Q',
'RD_Q',
'RT_Q',
'ASI_Q',
'PER_Q',
'REC_Q',
'TAP_Q',
'TAPR_Q',
'FP_Q',
'FPR_Q',
'MAT_Q',
'+/-_Q',
'VAL_Q'
]



equipo = [
'MIN_Eq',
'TCA_Eq',
'TCI_Eq',
'TCF_Eq',
'T2A_Eq',
'T2I_Eq',
'T2F_Eq',
'T3A_Eq',
'T3I_Eq',
'T3F_Eq',
'TLA_Eq',
'TLI_Eq',
'TLF_Eq',
'RO_Eq',
'RD_Eq',
'RT_Eq',
'ASI_Eq',
'PER_Eq',
'REC_Eq',
'TAP_Eq',
'TAPR_Eq',
'FP_Eq',
'FPR_Eq',
'MAT_Eq',
'VAL_Eq'
]



equipo_por_cuarto = [
'MIN_Eq_Q',
'PTS_Eq_Q',
'TCA_Eq_Q',
'TCI_Eq_Q',
'TCF_Eq_Q',
'T2A_Eq_Q',
'T2I_Eq_Q',
'T2F_Eq_Q',
'T3A_Eq_Q',
'T3I_Eq_Q',
'T3F_Eq_Q',
'TLA_Eq_Q',
'TLI_Eq_Q',
'TLF_Eq_Q',
'RO_Eq_Q',
'RD_Eq_Q',
'RT_Eq_Q',
'ASI_Eq_Q',
'PER_Eq_Q',
'REC_Eq_Q',
'TAP_Eq_Q',
'TAPR_Eq_Q',
'FP_Eq_Q',
'FPR_Eq_Q',
'MAT_Eq_Q',
'VAL_Eq_Q'
]

rival = [
'T2I_Rival',
'T3I_Rival',
'RD_Rival',
'RO_Rival',
'RT_Rival',
]

avanzadas = [
'POS_Eq',
'POS_Rival',
'PACE',
'ORtg',
'DRtg',
'NRtg',
'%TE_Eq',
'%TR_Eq',
'%ASI_Eq',
'%PER_Eq',
'%RO_Eq',
'%RD_Eq',
'%RT_Eq',
'RTL_Eq',
'RT3I_Eq',
'%T2_Eq',
'%T3_Eq',
'%TL_Eq',
'%USO',
'%TR',
'%TE',
'%ASI',
'%PER',
'%RO',
'%RD',
'%RT',
'%REC',
'%TAP',
'RTL',
'RT3I',
'PPT'
]

In [507]:
df['ID_Q'] = df['#'] + '_' + df['EQUIPO'] + '_J' + df['JORNADA'].astype(str) + '_Q' + df['CUARTO'].astype(str)
df['ID_partido'] = df['#'] + '_' + df['EQUIPO'] + '_J' + df['JORNADA'].astype(str)

id_q = ['ID_Q', 'CUARTO']

In [508]:
columnas_por_cuarto = id_q + base + por_cuarto + equipo_por_cuarto
columnas_por_partido = base + por_partido + equipo + avanzadas
columnas_total = base + por_cuarto + por_partido + equipo_por_cuarto + equipo + avanzadas

df_por_cuarto = df[columnas_por_cuarto]
df_por_partido = df[columnas_por_partido].drop_duplicates()
df_total = df[columnas_total]

In [509]:
len(df_por_cuarto)

3776

In [510]:
len(df_por_partido)

936

In [511]:
df_partidos

    JORNADA LOCAL  RESULTADO VISITANTE VICTORIA
0         1   UNI    86 - 68       SBB      UNI
1         1   BUR    97 - 79       GIR      BUR
2         1   LLT   104 - 93       BAX      LLT
3         1   HIO    87 - 68       BRE      HIO
4         1   COV    75 - 87       JOV      JOV
5         1   RMB    81 - 71       DGC      RMB
6         1   CAZ   107 - 88       BKN      CAZ
7         1   UCM    95 - 64       MBA      UCM
8         1   VBC    93 - 81       BAR      VBC
9         2   GIR    71 - 93       UCM      UCM
10        2   MBA    64 - 96       LLT      LLT
11        2   DGC    72 - 81       UNI      UNI
12        2   BAX    83 - 68       COV      BAX
13        2   JOV    89 - 86       CAZ      JOV
14        2   BAR    86 - 91       HIO      HIO
15        2   BRE   90 - 113       VBC      VBC
16        2   SBB    95 - 85       BUR      SBB
17        2   BKN  105 - 100       RMB      BKN
18        3   BAX    80 - 87       DGC      DGC
19        3   MBA  115 - 113       GIR      MBA
20        3   LLT    96 - 80       UCM      LLT
21        3   CAZ    84 - 88       BRE      BRE
22        3   JOV   101 - 69       SBB      JOV
23        3   RMB    90 - 80       BUR      RMB
24        3   HIO    78 - 99       VBC      VBC
25        3   COV    80 - 83       BKN      BKN
26        3   UNI    77 - 83       BAR      BAR
27        4   HIO    99 - 90       COV      HIO
28        4   BAR   100 - 85       BRE      BAR
29        4   LLT    95 - 79       UNI      LLT
30        4   BUR   89 - 102       CAZ      CAZ
31        4   GIR    85 - 81       DGC      GIR
32        4   UCM    89 - 84       BKN      UCM
33        4   SBB    81 - 71       MBA      SBB
34        4   VBC   102 - 90       JOV      VBC
35        4   RMB    87 - 75       BAX      RMB

# Export

In [512]:
df_por_cuarto.to_csv(
    PROCESSED_PATH/'Datos_acb_por_cuarto.csv',
    sep=';',
    decimal=',',
    index=False
)
df_por_partido.to_csv(
    PROCESSED_PATH/'Datos_acb_por_partido.csv',
    sep=';',
    decimal=',',
    index=False
)
df_total.to_csv(
    PROCESSED_PATH/'Datos_acb_total.csv',
    sep=';',
    decimal=',',
    index=False
)
df_partidos.to_csv(
    PROCESSED_PATH/'Partidos.csv',
    sep=';',
    decimal=',',
    index=False
)