In [258]:
import pandas as pd
import numpy as np

import warnings
from pathlib import Path
import unicodedata

pd.set_option("display.max_colwidth", None)



ROOT_PATH = Path(Path.cwd()).resolve().parent
DATA_PATH = ROOT_PATH/'data'/'processed'
PROCESSED_PATH = ROOT_PATH/'data'/'processed'

In [259]:
# df = pd.DataFrame(columns=[
#     'Equipo',
#     'Dorsal',
#     'Nombre',
#     'Apellido',
#     'Nombre_Completo',
#     'Posición',
#     'Altura',
#     'Fecha_Nacim',
#     'Pais_Nacim',
#     'Comunidad',
#     'Nacionalidad',
#     'Licencia'
# ])

In [260]:
df = pd.read_csv(
    DATA_PATH/'Jugadores.csv',
    dtype={
        "Equipo": "object",
        "Dorsal": "object",
        "Nombre": "object",
        "Apellido": "object",
        "Posición": "object",
        "Altura": "object",
        "Fecha_Nacim": "object",
        "Pais_Nacim": "object",
        "Comunidad": "object",
        "Nacionalidad": "object",
        "Licencia": "object"
    })

In [261]:
df.tail(3)

,Equipo,Dorsal,Nombre,Apellido,Nombre_Completo,Posición,Altura,Fecha_Nacim,Pais_Nacim,Comunidad,Nacionalidad,Licencia,Foto,Bandera_Pais,Bandera_Comunidad,KEY
19,JOV,10,Nico,Laprovittola,Nico Laprovittola,Base,190,31/01/1990,ARG,NO,ITA,EUR,https://github.com/DJordanV/ACB_26-27/blob/develop/img/clubes/JOV/cuerpo/10-laprovittola.webp?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ARG.png?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ESP/NO.png?raw=true,JOV10Laprovittola
20,JOV,12,Ludde,Hakanson,Ludde Hakanson,Base,189,22/03/1996,SWE,NO,SWE,JFL,https://github.com/DJordanV/ACB_26-27/blob/develop/img/clubes/JOV/cuerpo/12-hakanson.webp?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/SWE.png?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ESP/NO.png?raw=true,JOV12Hakanson
21,JOV,18,Álex,Reyes,Álex Reyes,Alero,202,17/12/1993,ESP,EXT,ESP,JFL,https://github.com/DJordanV/ACB_26-27/blob/develop/img/clubes/JOV/cuerpo/18-reyes.webp?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ESP.png?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ESP/EXTREMADURA.png?raw=true,JOV18Reyes

In [262]:
posiciones = {
    '1': 'Base',
    '2': 'Escolta',
    '3': 'Alero',
    '4': 'Ala-Pívot',
    '5': 'Pívot'
}
licencias = {
    '1': 'JFL',
    '2': 'EUR',
    '3': 'COT',
    '4': 'EXT'
}

In [263]:
equipo = input('Equipo: ').upper()

In [264]:
jugadores = []

while True:

    continuar = input('Añadir otro jugador? (S/N): ').upper()
    if continuar != 'S':
        break

    # equipo = input('Equipo: ').upper()
    dorsal = input('Dorsal: ')
    nombre = input('Nombre (sin apellido): ').title()
    apellido = input('Apellido: ').title()

    posicion = input('Posición (1=Base, 2=Escolta, 3=Alero, 4=Ala-Pívot, 5=Pívot): ')
    posicion = posiciones.get(posicion, 'Desconocida')

    altura = input('Altura en cm: ')
    dia_nacim = input('Día de nacimiento (DD): ')
    mes_nacim = input('Mes de nacimiento (MM): ')
    año_nacim = input('Año de nacimiento (AAAA): ')

    fecha_nacim = dia_nacim + '/' + mes_nacim + '/' + año_nacim
    
    pais_nacim = input('País de Nacimiento: ').upper()
    if pais_nacim in ['ESP', 'ESPAÑA']:
        comunidad = input('Comunidad Autónoma: ').upper()
    else:
        comunidad = 'NO'

    nacionalidad = input('Nacionalidad = País de Nacimiento? (s/n): ').upper()
    if nacionalidad != 'S':
        nacionalidad = input('Nacionalidad: ').upper()
    else:
        nacionalidad = pais_nacim

    licencia = input('Licencia (1=JFL, 2=EUR, 3=COT, 4=EXT): ').upper()
    if licencia in licencias:
        licencia = licencias.get(licencia, 'Desconocida')
    else:
        licencia = input('Licencia: ').upper()

    nueva_fila = {
        'Equipo': equipo,
        'Dorsal': dorsal,
        'Nombre': nombre,
        'Apellido': apellido,
        'Nombre_Completo': nombre + ' ' + apellido,
        'Posición': posicion,
        'Altura': altura,
        'Fecha_Nacim': fecha_nacim,
        'Pais_Nacim': pais_nacim,
        'Comunidad': comunidad,
        'Nacionalidad': nacionalidad,
        'Licencia': licencia
    }

    jugadores.append(nueva_fila)


df = pd.concat(
    [df, pd.DataFrame(jugadores)],
    ignore_index=True
)

In [273]:
iso_paises = {
    'ESPAÑA': 'ESP',
    'ARGENTINA': 'ARG',
    'ITALIA': 'ITA',
    'CHEQUIA': 'CZE',
    'SENEGAL': 'SEN',
    'FRANCIA': 'FRA',
    'GEORGIA': 'GEO',
    'MALI': 'MLI',
    'ESTONIA': 'EST',
    'PAISES BAJOS': 'NLD',
    'SERBIA': 'SRB',
    'CROACIA': 'HRV',
    'HUNGRIA': 'HUN',
    'MONTENEGRO': 'MNE',
    'REINO UNIDO': 'GBR',
    'LITUANIA': 'LTU',
    'SUECIA': 'SWE',
    'CANADA': 'CAN',
    'JAMAICA': 'JAM',
    'URUGUAY': 'URY',
    'RUSIA': 'RUS',
    'CHAD': 'TCD',
    'TURQUIA': 'TUR',
    'REPUBLICA CENTROAFRICANA': 'CAF',
    'REPUBLICA DOMINICANA': 'DOM',
    'CUBA': 'CUB',
    'RUMANIA': 'ROU',
    'ESLOVAQUIA': 'SVK',
    'GUINEA': 'GIN',
    'LETONIA': 'LVA',
    'BOSNIA Y HERZEGOVINA': 'BIH',
    'FINLANDIA': 'FIN'
}
df.replace(iso_paises, inplace=True)

iso_comunidades = {
    'MADRID': 'MAD',
    'CATALUÑA': 'CAT',
    'EXTREMADURA': 'EXT',
    'ANDALUCIA': 'AND',
    'ARAGON': 'ARA',
    'ASTURIAS': 'AST',
    'BALEARES': 'BAL',
    'CANARIAS': 'CAN',
    'CEUTA': 'CEU',
    'CANTABRIA': 'CTB'
}
df.replace(iso_comunidades, inplace=True)

In [274]:
# Comprobación de que todos los países aparecen con código ISO 3166-1 alfa-3

columnas = ["Pais_Nacim", "Comunidad", "Nacionalidad"]

for col in columnas:
    mask = df[col].notna() & (df[col].str.len() > 3)

    if mask.any():
        warnings.warn(
            f"La columna '{col}' contiene valores con más de 3 caracteres: "
            f"{df.loc[mask, col].unique().tolist()}",
            UserWarning
        )

In [275]:
df['Apellido_modif'] = (
    df["Apellido"]
    .str.lower()
    .apply(lambda x: unicodedata.normalize("NFD", x).encode("ascii", "ignore").decode("utf-8"))
)

df['Foto'] = 'https://github.com/DJordanV/ACB_26-27/blob/develop/img/clubes/' + df['Equipo'] + '/cuerpo/' + df['Dorsal'] + '-' + df['Apellido_modif'] + '.webp?raw=true'
df['Bandera_Pais'] = 'https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/' + df['Pais_Nacim'] + '.png?raw=true'
df['Bandera_Comunidad'] = 'https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ESP/' + df['Comunidad'] + '.png?raw=true'


df = df.drop(columns='Apellido_modif')

In [276]:
# df.loc[[6], 'Licencia'] = 'EUR'

In [277]:
# df = df.drop(15)

In [278]:
# Key que identifica al jugador de forma inequívoca

df['KEY'] = df['Equipo'] + df['Dorsal'] + df['Apellido']

In [279]:
df.tail(10)

,Equipo,Dorsal,Nombre,Apellido,Nombre_Completo,Posición,Altura,Fecha_Nacim,Pais_Nacim,Comunidad,Nacionalidad,Licencia,Foto,Bandera_Pais,Bandera_Comunidad,KEY
17,JOV,4,Eli,Ndiaye,Eli Ndiaye,Ala-Pívot,204,26/06/2004,SEN,NO,ESP,JFL,https://github.com/DJordanV/ACB_26-27/blob/develop/img/clubes/JOV/cuerpo/4-ndiaye.webp?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/SEN.png?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ESP/NO.png?raw=true,JOV4Ndiaye
18,JOV,9,Ricky,Rubio,Ricky Rubio,Base,189,21/10/1990,ESP,CAT,ESP,JFL,https://github.com/DJordanV/ACB_26-27/blob/develop/img/clubes/JOV/cuerpo/9-rubio.webp?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ESP.png?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ESP/CAT.png?raw=true,JOV9Rubio
19,JOV,10,Nico,Laprovittola,Nico Laprovittola,Base,190,31/01/1990,ARG,NO,ITA,EUR,https://github.com/DJordanV/ACB_26-27/blob/develop/img/clubes/JOV/cuerpo/10-laprovittola.webp?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ARG.png?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ESP/NO.png?raw=true,JOV10Laprovittola
20,JOV,12,Ludde,Hakanson,Ludde Hakanson,Base,189,22/03/1996,SWE,NO,SWE,JFL,https://github.com/DJordanV/ACB_26-27/blob/develop/img/clubes/JOV/cuerpo/12-hakanson.webp?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/SWE.png?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ESP/NO.png?raw=true,JOV12Hakanson
21,JOV,18,Álex,Reyes,Álex Reyes,Alero,202,17/12/1993,ESP,EXT,ESP,JFL,https://github.com/DJordanV/ACB_26-27/blob/develop/img/clubes/JOV/cuerpo/18-reyes.webp?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ESP.png?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ESP/EXT.png?raw=true,JOV18Reyes
22,JOV,19,Emir,Sulejmanovic,Emir Sulejmanovic,Ala-Pívot,205,13/07/1995,BIH,NO,FIN,EUR,https://github.com/DJordanV/ACB_26-27/blob/develop/img/clubes/JOV/cuerpo/19-sulejmanovic.webp?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/BIH.png?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ESP/NO.png?raw=true,JOV19Sulejmanovic
23,JOV,32,Isaac,Nogués,Isaac Nogués,Escolta,196,10/02/2004,ESP,CAT,ESP,JFL,https://github.com/DJordanV/ACB_26-27/blob/develop/img/clubes/JOV/cuerpo/32-nogues.webp?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ESP.png?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ESP/CAT.png?raw=true,JOV32Nogués
24,JOV,35,Simon,Birgander,Simon Birgander,Pívot,209,23/10/1997,SWE,NO,SWE,EUR,https://github.com/DJordanV/ACB_26-27/blob/develop/img/clubes/JOV/cuerpo/35-birgander.webp?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/SWE.png?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ESP/NO.png?raw=true,JOV35Birgander
25,JOV,44,Ante,Tomic,Ante Tomic,Pívot,217,17/02/1987,HRV,NO,HRV,EUR,https://github.com/DJordanV/ACB_26-27/blob/develop/img/clubes/JOV/cuerpo/44-tomic.webp?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/HRV.png?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ESP/NO.png?raw=true,JOV44Tomic
26,JOV,55,Kwan,Cheatham,Kwan Cheatham,Ala-Pívot,206,21/08/1995,USA,NO,USA,EUR,https://github.com/DJordanV/ACB_26-27/blob/develop/img/clubes/JOV/cuerpo/55-cheatham.webp?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/USA.png?raw=true,https://github.com/DJordanV/ACB_26-27/blob/develop/img/banderas/ESP/NO.png?raw=true,JOV55Cheatham

In [280]:
df.to_csv(
    PROCESSED_PATH/'Jugadores.csv',
    index=False
)