In [1]:
import pandas as pd
import numpy as np

import warnings
from pathlib import Path
import unicodedata

pd.set_option("display.max_colwidth", None)



ROOT_PATH = Path(Path.cwd()).resolve().parent
DATA_PATH = ROOT_PATH/'data'/'processed'
PROCESSED_PATH = ROOT_PATH/'data'/'processed'

In [2]:
# df = pd.DataFrame(columns=[
#     'Equipo',
#     'Dorsal',
#     'Nombre',
#     'Apellido',
#     'Posición',
#     'Altura',
#     'Fecha_Nacim',
#     'Pais_Nacim',
#     'Comunidad',
#     'Nacionalidad',
#     'Licencia'
# ])

In [3]:
df = pd.read_csv(
    DATA_PATH/'Jugadores.csv',
    dtype={
        "Equipo": "object",
        "Dorsal": "object",
        "Nombre": "object",
        "Apellido": "object",
        "Posición": "object",
        "Altura": "object",
        "Fecha_Nacim": "object",
        "Pais_Nacim": "object",
        "Comunidad": "object",
        "Nacionalidad": "object",
        "Licencia": "object"
    })

In [4]:
df.tail(10)

,Equipo,Dorsal,Nombre,Apellido,Posición,Altura,Fecha_Nacim,Pais_Nacim,Comunidad,Nacionalidad,Licencia,Foto,Bandera_Pais,Bandera_Comunidad
65,UCM,15,Emanuel,Cate,NaN,207,30/07/1997,ROU,NaN,ROU,JFL,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/15-cate.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ROU.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png
66,UCM,16,Rubén,López De La Torre,NaN,201,13/03/2002,ESP,MAD,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/16-lopez de la torre.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP/MAD.png?raw=true
67,UCM,20,Pablo,Sevilla,NaN,197,13/03/2007,ESP,MUR,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/20-sevilla.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP/MUR.png?raw=true
68,UCM,21,Moussa,Diagne,NaN,211,06/03/1994,SEN,NaN,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/21-diagne.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/SEN.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png
69,UCM,30,Kelan,Martin,NaN,201,03/08/1995,USA,NaN,USA,EXT,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/30-martin.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/USA.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png
70,UCM,31,Dylan,Ennis,NaN,188,26/12/1991,CAN,NaN,SRB,EUR,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/31-ennis.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/CAN.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png
71,UCM,50,Jaylen,Hands,NaN,191,12/02/1999,USA,NaN,USA,EXT,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/50-hands.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/USA.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png
72,UCM,99,Toni,Nakic,NaN,201,01/06/1999,HRV,NaN,HRV,EUR,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/99-nakic.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/HRV.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png
73,UCM,6,Dani,García,NaN,185,30/01/1998,ESP,CAT,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/6-garcia.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP/CAT.png?raw=true
74,UCM,24,Zach,Hicks,NaN,203,22/04/2003,USA,NaN,USA,EXT,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/24-hicks.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/USA.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png

In [5]:
jugadores = []


while True:

    continuar = input('Añadir otro jugador? (S/N): ').upper()
    if continuar != 'S':
        break

    equipo = input('Equipo: ').upper()
    dorsal = input('Dorsal: ')
    nombre = input('Nombre (sin apellido): ').title()
    apellido = input('Apellido: ').title()
    posicion = input('Posición: ')
    altura = input('Altura en cm: ')

    dia_nacim = input('Día de nacimiento (DD): ')
    mes_nacim = input('Mes de nacimiento (MM): ')
    año_nacim = input('Año de nacimiento (AAAA): ')
    fecha_nacim = dia_nacim + '/' + mes_nacim + '/' + año_nacim
    
    pais_nacim = input('País de Nacimiento: ').upper()

    if pais_nacim in ['ESP', 'ESPAÑA']:
        comunidad = input('Comunidad Autónoma: ').upper()
    else:
        comunidad = ''

    nacionalidad = input('Nacionalidad: ').upper()
    licencia = input('Licencia: ').upper()

    nueva_fila = {
        'Equipo': equipo,
        'Dorsal': dorsal,
        'Nombre': nombre,
        'Apellido': apellido,
        'Posición': posicion,
        'Altura': altura,
        'Fecha_Nacim': fecha_nacim,
        'Pais_Nacim': pais_nacim,
        'Comunidad': comunidad,
        'Nacionalidad': nacionalidad,
        'Licencia': licencia
    }

    jugadores.append(nueva_fila)


df = pd.concat(
    [df, pd.DataFrame(jugadores)],
    ignore_index=True
)

In [6]:
iso_paises = {
    'ESPAÑA': 'ESP',
    'ARGENTINA': 'ARG',
    'ITALIA': 'ITA',
    'CHEQUIA': 'CZE',
    'SENEGAL': 'SEN',
    'FRANCIA': 'FRA',
    'GEORGIA': 'GEO',
    'MALI': 'MLI',
    'ESTONIA': 'EST',
    'PAISES BAJOS': 'NLD',
    'SERBIA': 'SRB',
    'CROACIA': 'HRV',
    'HUNGRIA': 'HUN',
    'MONTENEGRO': 'MNE',
    'REINO UNIDO': 'GBR',
    'LITUANIA': 'LTU',
    'SUECIA': 'SWE',
    'CANADA': 'CAN',
    'JAMAICA': 'JAM',
    'URUGUAY': 'URY',
    'RUSIA': 'RUS',
    'CHAD': 'TCD',
    'TURQUIA': 'TUR',
    'REPUBLICA CENTROAFRICANA': 'CAF',
    'REPUBLICA DOMINICANA': 'DOM',
    'CUBA': 'CUB',
    'RUMANIA': 'ROU',
    'ESLOVAQUIA': 'SVK',
}
df.replace(iso_paises, inplace=True)

C:\Users\jorda\AppData\Local\Temp\ipykernel_31968\2060890997.py:31: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(iso_paises, inplace=True)

In [7]:
df['Apellido_modif'] = (
    df["Apellido"]
    .str.lower()
    .apply(lambda x: unicodedata.normalize("NFD", x).encode("ascii", "ignore").decode("utf-8"))
)

df['Foto'] = 'https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/' + df['Equipo'] + '/cuerpo/' + df['Dorsal'] + '-' + df['Apellido_modif'] + '.webp?raw=true'
df['Bandera_Pais'] = 'https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/' + df['Pais_Nacim'] + '.png?raw=true'
df['Bandera_Comunidad'] = np.where(df['Comunidad'] == '', '', 'https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP/' + df['Comunidad'] + '.png?raw=true')
df['Bandera_Comunidad'] = np.where(df['Bandera_Comunidad'].isna(), 'https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png', df['Bandera_Comunidad'])


df = df.drop(columns='Apellido_modif')

In [8]:
columnas = ["Pais_Nacim", "Comunidad", "Nacionalidad"]

for col in columnas:
    mask = df[col].notna() & (df[col].str.len() > 3)

    if mask.any():
        warnings.warn(
            f"La columna '{col}' contiene valores con más de 3 caracteres: "
            f"{df.loc[mask, col].unique().tolist()}",
            UserWarning
        )

In [9]:
df.tail(10)

,Equipo,Dorsal,Nombre,Apellido,Posición,Altura,Fecha_Nacim,Pais_Nacim,Comunidad,Nacionalidad,Licencia,Foto,Bandera_Pais,Bandera_Comunidad
65,UCM,15,Emanuel,Cate,NaN,207,30/07/1997,ROU,NaN,ROU,JFL,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/15-cate.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ROU.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png
66,UCM,16,Rubén,López De La Torre,NaN,201,13/03/2002,ESP,MAD,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/16-lopez de la torre.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP/MAD.png?raw=true
67,UCM,20,Pablo,Sevilla,NaN,197,13/03/2007,ESP,MUR,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/20-sevilla.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP/MUR.png?raw=true
68,UCM,21,Moussa,Diagne,NaN,211,06/03/1994,SEN,NaN,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/21-diagne.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/SEN.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png
69,UCM,30,Kelan,Martin,NaN,201,03/08/1995,USA,NaN,USA,EXT,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/30-martin.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/USA.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png
70,UCM,31,Dylan,Ennis,NaN,188,26/12/1991,CAN,NaN,SRB,EUR,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/31-ennis.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/CAN.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png
71,UCM,50,Jaylen,Hands,NaN,191,12/02/1999,USA,NaN,USA,EXT,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/50-hands.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/USA.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png
72,UCM,99,Toni,Nakic,NaN,201,01/06/1999,HRV,NaN,HRV,EUR,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/99-nakic.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/HRV.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png
73,UCM,6,Dani,García,NaN,185,30/01/1998,ESP,CAT,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/6-garcia.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP/CAT.png?raw=true
74,UCM,24,Zach,Hicks,NaN,203,22/04/2003,USA,NaN,USA,EXT,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/24-hicks.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/USA.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png

In [10]:
# df.loc[[73], 'Fecha_Nacim'] = '30/01/1998'

In [11]:
# df = df.drop(21)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Equipo             75 non-null     object
 1   Dorsal             75 non-null     object
 2   Nombre             75 non-null     object
 3   Apellido           75 non-null     object
 4   Posición           0 non-null      float64
 5   Altura             75 non-null     object
 6   Fecha_Nacim        75 non-null     object
 7   Pais_Nacim         75 non-null     object
 8   Comunidad          20 non-null     object
 9   Nacionalidad       75 non-null     object
 10  Licencia           75 non-null     object
 11  Foto               75 non-null     object
 12  Bandera_Pais       75 non-null     object
 13  Bandera_Comunidad  75 non-null     object
dtypes: float64(1), object(13)
memory usage: 8.3+ KB

In [13]:
posiciones = {
    "1": "Base",
    "2": "Escolta",
    "3": "Alero",
    "4": "Ala-Pívot",
    "5": "Pívot"
}

for i, fila in df.iterrows():
    print(f"\nJugador: {fila['Dorsal']} {fila['Nombre']} {fila['Apellido']} ({fila['Equipo']})")  # Cambia 'Apellido' por el nombre real de tu columna
    
    while True:
        posicion = input(
            "Posición (1=Base, 2=Escolta, 3=Alero, 4=Ala-Pívot, 5=Pívot): "
        )
        
        if posicion in posiciones:
            df.at[i, "Posición"] = posiciones[posicion]
            break
        else:
            print("Valor no válido. Introduce un número del 1 al 5.")

Jugador: 0 Henri Drell (JOV)

C:\Users\jorda\AppData\Local\Temp\ipykernel_31968\2453342780.py:18: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Ala-Pívot' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[i, "Posición"] = posiciones[posicion]

Jugador: 1 Yannick Kraag (JOV)

Jugador: 9 Ricky Rubio (JOV)

Jugador: 11 Jabari Parker (JOV)

Jugador: 12 Ludde Hakanson (JOV)

Jugador: 16 Guillem Vives (JOV)

Jugador: 20 Adrián Torres (JOV)

Jugador: 21 Miguel Allen (JOV)

Jugador: 22 Humberto Ruiz (JOV)

Jugador: 23 Michael Ruzic (JOV)

Jugador: 24 Cameron Hunt (JOV)

Jugador: 25 Yannis Morin (JOV)

Jugador: 32 Ferran Mauri (JOV)

Jugador: 34 Diego Niebla (JOV)

Jugador: 35 Simon Birgander (JOV)

Jugador: 44 Ante Tomic (JOV)
Valor no válido. Introduce un número del 1 al 5.

Jugador: 88 Adam Hanga (JOV)

Jugador: 17 Sam Dekker (JOV)

Jugador: 0 Kevin Punter (BAR)

Jugador: 2 Juani Marcos (BAR)

Jugador: 3 Myles Cale (BAR)
Valor no válido. Introduce un número del 1 al 5.

Jugador: 5 Miles Norris (BAR)

Jugador: 6 Jan Vesely (BAR)

Jugador: 8 Darío Brizuela (BAR)

Jugador: 13 Tomas Satoransky (BAR)

Jugador: 14 Willy Hernangómez (BAR)

Jugador: 17 Juan Núñez (BAR)

Jugador: 19 Youssoupha Fall (BAR)

Jugador: 20 Nico Laprovittola (BAR)

Jugador: 21 Will Clyburn (BAR)

Jugador: 23 Tornike Shengelia (BAR)

Jugador: 41 Sayon Keita (BAR)

Jugador: 43 Nikola Kusturica (BAR)

Jugador: 44 Joel Parra (BAR)

Jugador: 47 Dani González (BAR)
Valor no válido. Introduce un número del 1 al 5.

Jugador: 0 Marco Spissu (CAZ)

Jugador: 00 Devin Robinson (CAZ)

Jugador: 2 Trae Bell-Haynes (CAZ)
Valor no válido. Introduce un número del 1 al 5.

Jugador: 3 Justin Wright-Foreman (CAZ)

Jugador: 4 Santi Yusta (CAZ)

Jugador: 7 Miguel González (CAZ)

Jugador: 9 Matija Lukic (CAZ)

Jugador: 10 Jaime Fernández (CAZ)

Jugador: 11 Gabriel Olaseni (CAZ)

Jugador: 14 Bojan Dubljevic (CAZ)

Jugador: 15 Joaquín Rodríguez (CAZ)

Jugador: 17 Carlos Alías (CAZ)

Jugador: 18 Aleksandr Savkov (CAZ)

Jugador: 20 Dj Stephens (CAZ)

Jugador: 21 Christ Koumadje (CAZ)

Jugador: 23 Youssouf Traoré (CAZ)

Jugador: 3 Erik Stevenson (CAZ)

Jugador: 5 Lucas Langarita (CAZ)

Jugador: 5 Isaiah Washington (CAZ)

Jugador: 8 Emir Kabaca (CAZ)

Jugador: 11 Josh Richardson (CAZ)

Jugador: 12 Joel Soriano (CAZ)

Jugador: 0 Devontae Cacok (UCM)

Jugador: 1 Michael Forrest (UCM)

Jugador: 2 Sander Raieste (UCM)

Jugador: 3 José Tomás Martínez (UCM)

Jugador: 5 David Dejulius (UCM)
Valor no válido. Introduce un número del 1 al 5.

Jugador: 8 Howard Sant-Roos (UCM)

Jugador: 12 Jonah Radebaugh (UCM)

Jugador: 13 Wilhelm Falk (UCM)

Jugador: 15 Emanuel Cate (UCM)
Valor no válido. Introduce un número del 1 al 5.

Jugador: 16 Rubén López De La Torre (UCM)

Jugador: 20 Pablo Sevilla (UCM)

Jugador: 21 Moussa Diagne (UCM)
Valor no válido. Introduce un número del 1 al 5.

Jugador: 30 Kelan Martin (UCM)

Jugador: 31 Dylan Ennis (UCM)

Jugador: 50 Jaylen Hands (UCM)

Jugador: 99 Toni Nakic (UCM)

Jugador: 6 Dani García (UCM)

Jugador: 24 Zach Hicks (UCM)
Valor no válido. Introduce un número del 1 al 5.

In [16]:
df['KEY'] = df['Equipo'] + df['Dorsal'] + df['Apellido']

In [18]:
df

,Equipo,Dorsal,Nombre,Apellido,Posición,Altura,Fecha_Nacim,Pais_Nacim,Comunidad,Nacionalidad,Licencia,Foto,Bandera_Pais,Bandera_Comunidad,KEY
0,JOV,0,Henri,Drell,Ala-Pívot,206,25/04/2000,EST,NaN,EST,EUR,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/JOV/cuerpo/0-drell.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/EST.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png,JOV0Drell
1,JOV,1,Yannick,Kraag,Alero,202,16/10/2002,NLD,NaN,NLD,JFL,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/JOV/cuerpo/1-kraag.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/NLD.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png,JOV1Kraag
2,JOV,9,Ricky,Rubio,Base,189,21/10/1990,ESP,CAT,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/JOV/cuerpo/9-rubio.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP/CAT.png?raw=true,JOV9Rubio
3,JOV,11,Jabari,Parker,Ala-Pívot,203,15/03/1995,USA,NaN,USA,EXT,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/JOV/cuerpo/11-parker.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/USA.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png,JOV11Parker
4,JOV,12,Ludde,Hakanson,Base,189,22/03/1996,SWE,NaN,SWE,JFL,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/JOV/cuerpo/12-hakanson.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/SWE.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png,JOV12Hakanson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,UCM,31,Dylan,Ennis,Escolta,188,26/12/1991,CAN,NaN,SRB,EUR,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/31-ennis.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/CAN.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png,UCM31Ennis
71,UCM,50,Jaylen,Hands,Escolta,191,12/02/1999,USA,NaN,USA,EXT,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/50-hands.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/USA.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png,UCM50Hands
72,UCM,99,Toni,Nakic,Alero,201,01/06/1999,HRV,NaN,HRV,EUR,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/99-nakic.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/HRV.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png,UCM99Nakic
73,UCM,6,Dani,García,Base,185,30/01/1998,ESP,CAT,ESP,JFL,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/6-garcia.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/ESP/CAT.png?raw=true,UCM6García
74,UCM,24,Zach,Hicks,Ala-Pívot,203,22/04/2003,USA,NaN,USA,EXT,https://github.com/DJordanV/ACB_25-26/blob/develop/img/clubes/UCM/cuerpo/24-hicks.webp?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/banderas/USA.png?raw=true,https://github.com/DJordanV/ACB_25-26/blob/develop/img/pixel_empty.png,UCM24Hicks

In [19]:
df.to_csv(
    PROCESSED_PATH/'Jugadores.csv',
    index=False
)